FROM node:20

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN yarn install

# Copy application code
COPY . .

# Expose the port
EXPOSE 3000

# Command to run the development server
CMD ["yarn", "dev"]
